/* AUTO-GENERATED by scripts/blur.mjs — do not edit by hand. */

export const BLUR = {
  "baklava": { w: 1200, h: 900, blur: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwABABoJbACdAYvNgFU32EAAP4HSdfrvGBrUf8qJm745byH0V4x+n86U2DMDpE1ewvWCDlA8RZp7Nrkg+STig8OK7gz4nsItp3Kbb7vjH1a9FRk92wA" },
  "charcoal-grill": { w: 1600, h: 600, blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAYABABoJbACdAEeoWzhUgAAzKKuu7r+7KGruq9JJ84CQ+QzZFLoSrda9yHvw/7dEDS7WrasTxaW7NYof7/IlS5v4AAA" },
  "chicken-shawarma": { w: 1200, h: 900, blur: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAwABABoJbACdAEOefTYgAD+wH+DAYTJ+h9lSRFVAiQCHRQTvJun47w0kERVKUaurY6UNx/d5QF71iwbf1hKurkogAAA" },
  "doner-dark": { w: 1200, h: 900, blur: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAwABABoJbACdAYt9VmEFsuo5uIA/vahAu2NHdEbChZf/gWS2fW4/P4kzjw/QyXn4Dvl2UtUKzto5VQyKB/MGf9cgxdQD2D8w7ZNDXhvLOVCsQVF2FD6y2FJsiiAAAA=" },
  "flame": { w: 1600, h: 900, blur: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwAQCdASoQAAkABABoJbACdAEFpwkAAOJ9LfwzAhGzJFWUFRFiAVjhIkKkAWKDwS6WjjmO36z2OyGNJ4z+C4J8uZetKTyX4gGKjUnPz+y3CdZM90X7eIkKOvF21gcoSREPAAAA" },
  "hero-lamb-doner": { w: 1100, h: 736, blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsABABoJbACdAYvDlTusgAA+MUoZE16Pw/UEjdL0z5vUoJUk/8fpCUPThsUac/CB+QL+3oez8PB+iPEw3L07x0CzTX+BEJqe+1mj3fLAxa+J3uEAA==" },
  "mezze-spread": { w: 1200, h: 900, blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwABABoJZACdAXP+WlSihbIAP7RyqZrbNr1M5sGnyE4PTfPtQF+ezEEk078mmaRKeTShbpbP2yNf6DvL72QEexzMIAPquQ7bzA7NcxVrSxWJ6/AAA==" },
  "spit-carving": { w: 900, h: 1200, blur: "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoQABUAPxFysFAsJqSisAgBgCIJYgCdMoACblktM5N3Jln52wAA/oRap47U1xtScTwJth/vYqt00uX595g2SZqC2eKQodeSuhT8fe44/IcRjV1CtMyt7FhZVEk4rMBoAOzzji+AzhkZ0XBtmHMV0q9yCQAAAA==" },
  "venue": { w: 1600, h: 900, blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkABABoJQBOkDgC9kJJEqkgAP7p/3BYgX+U4CftczEDZ9K9HjAdQhu2urDU0jAFubaI1JXuyIEeYkBxUsuWuMi9S8N0rBQ7/YegiMW74/WrIkCAAA==" },
} as const;
