/**
 * Regenerates src/lib/blur.generated.ts from whatever is in public/img.
 *
 * Every hero-scale photograph gets a 16px-wide WebP encoded as a data URI, so
 * next/image can paint a blurred stand-in on the first frame. Static export has
 * no image optimizer, which means no automatic blurDataURL — this fills that
 * gap at build authoring time rather than at runtime.
 *
 *   node scripts/blur.mjs
 */
import sharp from "sharp";
import { readdirSync, writeFileSync } from "node:fs";

const DIR = "public/img";

const files = readdirSync(DIR)
  .filter((f) => f.endsWith(".webp"))
  .sort();

const rows = [];
for (const file of files) {
  const name = file.replace(/\.webp$/, "");
  const meta = await sharp(`${DIR}/${file}`).metadata();
  const tiny = await sharp(`${DIR}/${file}`)
    .resize(16, Math.max(1, Math.round((16 * meta.height) / meta.width)), { fit: "cover" })
    .webp({ quality: 30 })
    .toBuffer();
  rows.push(
    `  "${name}": { w: ${meta.width}, h: ${meta.height}, blur: "data:image/webp;base64,${tiny.toString("base64")}" },`,
  );
}

writeFileSync(
  "src/lib/blur.generated.ts",
  `/* AUTO-GENERATED by scripts/blur.mjs — do not edit by hand. */\n\nexport const BLUR = {\n${rows.join("\n")}\n} as const;\n`,
);

console.log(`wrote src/lib/blur.generated.ts with ${rows.length} entries`);
